### ISSUE TITLE
Crash when initialising a view controller with performance tracking enabled

### ISSUE THREAD

**Issue by rukano** [getsentry/sentry-cocoa#1355]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-cocoa 7.3.0

### Steps to Reproduce

1. iOS 15
2. Sentry 7.3.0
3. As a workaround we disabled the network performance tracking as mentioned in: https://github.com/getsentry/sentry-cocoa/issues/1346
4. In the SDK initialisation:
```swift
SentrySDK.start { options in
    // Temporary workaround to avoid memory crashes
    // See: https://github.com/getsentry/sentry-cocoa/issues/1346
    // Disable network tracking integration:
    options.integrations = options.integrations?.filter { $0 != "SentryNetworkTrackingIntegration" }
}
```

### Expected Result

Sentry would work with deactivated network performance tracking

### Actual Result

Sentry crashing quite often, when initialisation ViewControllers. Sentry issue message:

```
NSInternalInconsistencyException
UIViewController is missing its initial trait collection populated during initialization. This is a serious bug, likely caused by accessing properties or methods on the view controller before calling a UIViewController initializer. View controller: <MyViewController: 0x10101a000>
```

Stack trace from a reproduced crash via TestFlight.

![Sentry-Crash-iOS15](https://user-images.githubusercontent.com/97139/135426929-6b6d1cb0-f7d9-42be-bfb8-2246c35ffcc6.png)

Raw Crash log, retrieved from Sentry

[sentry-crash-log.txt](https://github.com/getsentry/sentry-cocoa/files/7258420/sentry-crash-log.txt)

Seem like the swizzling of VCs is giving problems in iOS 15, regarding the non-intialized trait collection(s)

**Comment by rukano** [comment]
Hi @philipphofmann the app was working well on iOS 14 and I was able to reproduce the crash only when I updated to iOS 15 (same build). Also some colleagues were saying the app on iOS 14 was still working, while the iOS 15 users were crashing. Also the sentry entries say 100% iOS 15, for this kind of crash.

**Comment by AndrewSB** [comment]
i'm seeing this as well, on iOS 15. i downgraded back to 7.3.0

it seems to crash 100% of the time a specific view is presented

**Comment by philipphofmann** [comment]
@AndrewSB, so you don't have the issue on `7.3.0`, because @rukano is having it on `7.3.0`? Which version did you encounter the error?

**Comment by philipphofmann** [comment]
I was looking at the stacktrace and our swizzling and wasn't able to find a problem. According to your stacktrace, you use `UINavigationController`. Therefore, I tried to reproduce your issue with a [sample project](https://github.com/Yalantis/AppearanceNavigationController) that uses `UINavigationController`, but it worked fine.

According to the stacktrace, first, the `SomeViewController.viewDidLoad` is called, which we intercept with swizzling. This seems to work fine as the stacktrace continues. Then the actual `SomeViewController.viewDidLoad` is called. After that, the `UITableViewController` is deallocated and then `UIViewController traitCollection` throws the error, caused by another `AnotherViewController`.

```
-[UIViewController traitCollection]                                         
-[UITableViewController dealloc]
SomeViewController.viewDidLoad (SomeViewController.swift:83)
SomeViewController.viewDidLoad
//  SentrySwizzle and Performance
__55+[SentryUIViewControllerSwizziling swizzleViewDidLoad:]_block_invoke_2 
-[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]
-[UIViewController loadViewIfRequired]
-[UIViewController view]
```

I would like to understand the relationship between `SomeViewController` and `AnotherViewController`. I don't fully understand how our swizzling messes up the `AnotherViewController`. Furthermore, our swizzling and performance code doesn't touch any of the properties of the ViewControllers. The only thing that I can think of causing problems right now could be our associated objects, which I will investigate further tomorrow.

Can you help me reproduce the issue or give me more context on your project, @rukano or @AndrewSB?

**Comment by AndrewSB** [comment]
i don't believe i'm seeing it on 7.3.0, i've downgraded and i'm not seeing it anymore

here's a crash log [Crash#245.txt](https://github.com/getsentry/sentry-cocoa/files/7261755/Crash.245.txt), i'm not sure exactly what about this reproduces the problem, but the hierarchy i'm loading when i crash is 

UINavigationController 
  -> UIViewController 
    -> child UIViewController
      -> child UIPageViewController
        -> Pages (which are UIViewControllers)
   
when i load the second page in my UIPageViewController, sentry performance crashes. the pages are all the same UIViewController subclass, not sure if that was helpful!

**Comment by rukano** [comment]
Hi @AndrewSB, I might be able to provide more information maybe tomorrow. But for the moment, a suspect that I have is, that the crashing VC has a custom initialiser. Something like this, but I haven't been able to make an example project to test it, sorry:

```swift
class SomeVC: UIViewController {
 	static func from(dependency: Any) -> Self {
 		let storyboard = UIStoryboard(name: "AStoryboard", bundle: .main)
 		guard let vc = storyboard.instantiateInitialViewController() as? Self else {
 			fatalError()
 		}
 		vc.dependency = dependency
 		return vc
 	}  
}
```

And then when pressing a button in the current view controller:

```swift
let vc = SomeVC.from(dependency: "whatever")
navigationController?.pushViewController(vc, animated: true)
```

That this way or instantiating the VC doesn't play well with the performance tracking?

I'll try this tomorrow more detailed and try to reproduce it in a minimal setup, but it was just a hunch, after checking some of the (thousands) crash issues 😅

**Comment by AndrewSB** [comment]
oh yeah! my VC in question totally has a custom initializer 

```swift
  init(tapped: @escaping (WardrobeItem) -> Void, deselect: @escaping (CharacterCatalogModel.Page) -> Void, onPrefetch: @escaping () -> Void) {
    // ...
    super.init(nibName: nil, bundle: nil)
}
```

that might be it

**Comment by brustolin** [comment]
@AndrewSB could you test putting @objc before your init?

```swift 
@objc init(tapped: @escaping (WardrobeItem) -> Void, deselect: @escaping (CharacterCatalogModel.Page) -> Void, onPrefetch: @escaping () -> Void) {
    // ...
    super.init(nibName: nil, bundle: nil)
}
```

I did some research and looks like this is some iOS 15 bug.

I got the same error using this class:

```swift
class CustomTableViewController : UITableViewController {
 
    var data:String?
    
    convenience init() {
        self.init(data: "test")
    }
    
    init(data: String) {
        super.init(style: .plain)
        self.data = data
    }
        
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
    
}
```

And I fixed it using @objc before the `init(data: String`.

**Comment by philipphofmann** [comment]
The init of `CustomTableViewController` crashes for with the same error in an empty sample project on iOS 15. It works fine on iOS 14 though. It seems like Apple generally speaking has an issue with custom ViewController initializers.

**Comment by philipphofmann** [comment]
Are you sure @rukano and @AndrewSB that the SentrySDK is causing the issue? Can you try not initializing the SentrySDK and see if the app still crashes? As pointed out in the comment above, the crash you are seeing could be a bug in UIKit and not related to our SDK at all.

**Comment by AndrewSB** [comment]
thanks for digging into this, that crashlog you posted on the apple forums looks very similar to the one i was experiencing. what seems strange is that the crash disappeared once i downgraded my sentry version.

i'm releasing a TestFlight later today, i'll add `@objc` to my initializer, and re-upgrade to 7.4.0 and see if i still experience a crash

**Comment by rukano** [comment]
> Are you sure @rukano and @AndrewSB that the SentrySDK is causing the issue? Can you try not initializing the SentrySDK and see if the app still crashes?

We released a version with 7.3.0 but with the performance tracking disabled and this has fixed the crashes. Haven't added any `@objc` or other workarounds than just deactivating the performance tracking.

**Comment by brustolin** [comment]
> We released a version with 7.3.0 but with the performance tracking disabled and this has fixed the crashes. Haven't added any `@objc` or other workarounds than just deactivating the performance tracking.

Thanks, I'm gonna investigate more into it.

**Comment by philipphofmann** [comment]
My current guess is that it has to do something with the swizzling of the initializers of the ViewControllers.

**Comment by philipphofmann** [comment]
We are drafting a different approach to swizzle all `UIViewControllers` without swizzling its initializers in #1361, which could maybe be the fix for this issue. Can you @rukano or/and @AndrewSB perhaps help us out with a repro in the meantime? That would be awesome.

**Comment by philipphofmann** [comment]
@rukano, testing the PR would be awesome, thanks. It's almost ready for merging. Thanks for the hint with the release configuration. Maybe code stripping is more aggressive for iOS 15. Anyway, I think and hope that #1361 fixes the bug. Even if it doesn't, we want to merge the PR as we don't want to swizzle the initializers of the UIViewControllers.
