### ISSUE TITLE
Frames remain unsymbolicated and shows <redacted>

### ISSUE THREAD

**Issue by ialimz** [getsentry/sentry-cocoa#1591]
### Environment

self-hosted

Which SDK and version?
7.5.4

### Steps to Reproduce

1. Open an issues
2. Frames of Main target in stack trace shows <redacted>

### Expected Result

While dSYM files are uploaded successfully, frames should be symbolicated and show exact file in stack trace.
I think this issue happened after migrating to Xcode 13.

### Actual Result

**Stack Trace:**
<img width="453" alt="Screen Shot 1400-10-06 at 10 53 32" src="https://user-images.githubusercontent.com/17988710/147446187-bd129612-d381-49c9-8c1a-3698722e8393.png">

**Images Status:**
<img width="502" alt="Screen Shot 1400-10-06 at 10 54 33" src="https://user-images.githubusercontent.com/17988710/147446298-abb7eaef-fc21-452b-ac57-b90ed7e56701.png">

**dSYM Upload Proof:**
<img width="1167" alt="Screen Shot 1400-10-06 at 10 55 17" src="https://user-images.githubusercontent.com/17988710/147446377-cb13a9bc-5214-4cb2-a2dc-09a189e03bb9.png">

**Comment by philipphofmann** [comment]
Hey @ialimz, can you give me details of your project, please? Which platform, programming language, etc. Could you maybe share a link to one of your issues here so that we can have a look?

**Comment by ialimz** [comment]
@philipphofmann It's an iOS Project written in Swift.
[Here](https://sentry-new.divar.ir/share/issue/81df495d46014bc38f29b9551add2b02/) is the link

**Comment by philipphofmann** [comment]
Which Swift version do you use, @ialimz? Maybe this is similar to https://github.com/getsentry/sentry-cocoa/issues/1502, which was fixed by updating our Swift demangler with https://github.com/getsentry/symbolic/pull/465. Can you make sure you run the latest version of Sentry, please?

**Comment by philipphofmann** [comment]
I just found our native team needs to bump some dependencies somewhere so you get https://github.com/getsentry/symbolic/pull/465 for self hosted. I'm not an expert on this so I can't tell you when this is going to happen.

**Comment by ialimz** [comment]
Swift version we've used is 5.5.2 @philipphofmann

**Comment by ialimz** [comment]
thanks @philipphofmann 
We will update our sentry panel and update this thread based on results

**Comment by ialimz** [comment]
@philipphofmann 
We've updated Sentry panel and Symbolicator. Issues still shows main target frames as <redacted>

**Comment by philipphofmann** [comment]
Thanks, for letting me know, @ialimz. According to @jan-auer, we didn't bump the dependencies for self-hosted yet for symbolicator. As most of these folks are on vacation till Monday, we have to wait a bit. I'm going to let you know when you can update Sentry and retry it.

**Comment by ialimz** [comment]
Thanks @philipphofmann

**Comment by philipphofmann** [comment]
Hey @ialimz, we will release a new version on January the 15th at 16:00 UTC. Please try again and let us know then.

**Comment by ialimz** [comment]
@philipphofmann I didn't find any updated library on 15th of the January. Would you please tell me which repository I should consider?

**Comment by philipphofmann** [comment]
This one https://github.com/getsentry/self-hosted, but we just realized something didn't work there. Will let you know once we fixed it.

**Comment by philipphofmann** [comment]
We fixed the release, see https://github.com/getsentry/self-hosted/releases/tag/22.1.0. Please try to update now @ialimz.

**Comment by ialimz** [comment]
@philipphofmann We updated our sentry panel to 22.1.0 and still frames are unsymbolicated. <redacted>.
Note that older versions (versions compiled on Xcode 12 and earlier) still works fine.
So I think something is wrong with Xcode 13 or Swift 5 and later versions

**Comment by ialimz** [comment]
It seems that frames are symbolicating now. This issue can be closed

**Comment by brustolin** [comment]
Thanks @ialimz
