### ISSUE TITLE
Xcode 16: Validation completed with warnings

### ISSUE THREAD

**Issue by andr-ec** [getsentry/sentry-cocoa#4068]
### Platform

iOS

### Environment

Other

### Installed

Swift Package Manager

### Version

8.29.0

### Xcode Version

16.0 beta 16A5171c

### Did it work on previous versions?

yes, latest 15 version

### Steps to Reproduce

1 archive build
2 click on validation button in organizer

I've tried with both The Sentry, Sentry dynamic, and sentry swift ui library.
I've also tried to reinstall with the wizard
I've also tried clearing the cache and the derived data.

### Expected Result

validate without warnings

### Actual Result

Upload Symbols Failed
The archive did not include a dSYM for the Sentry.framework with the UUIDs [17023652-04E3-34E2-8E8B-4F74918EDD6E]. Ensure that the archive's dSYM folder includes a DWARF file for Sentry.framework with the expected UUIDs.

**Comment by brustolin** [comment]
Thanks @andr-ec  for reaching out.
This is interesting, Apple probably have a new process to upload Symbols in there own validate process.
We will need to investigate this with Xcode 16.

**Comment by philipphofmann** [comment]
I can reproduce the problem by using SPM in our iOS-Swift sample app and validating it as described above. I committed the changed to a branch https://github.com/getsentry/sentry-cocoa/tree/repro/4068.

![CleanShot 2024-06-14 at 10 20 10@2x](https://github.com/getsentry/sentry-cocoa/assets/2443292/9c0930e5-e894-4c6b-b4b6-3c4f2758d670)

**Comment by philipphofmann** [comment]
Both XCArchives from Xcode 15 and Xcode don't contain dSYMs for Sentry in the `dSYMs` folder. So, I guess this is a new warning in Xcode 16.

**Comment by philipphofmann** [comment]
@andr-ec, have you encountered any actual problems after seeing this warning? Maybe it's a bug in Xcode.

**Comment by brustolin** [comment]
We need to check whether this have anything to do with the "new" Dwarf 5 standard of Xcode.

**Comment by calebhearth** [comment]
I'm still seeing this on beta 3 as part of uploading to App Store Connect.

![Image](https://github.com/user-attachments/assets/e83e8331-e214-48d3-b161-e2f7fb15e8ef)

**Comment by brustolin** [comment]
Same for Beta 5, this probably is here to stay, but it happens only for the static version of the framework, which can't have symbols (afaik). 

![Image](https://github.com/user-attachments/assets/b2b14c61-e5dd-4a6b-aa82-4d42a70cb3b2)

**Comment by denrase** [comment]
Could reproduce this issue for static `Sentry` using SPM. When using `Sentry-Dynamic`, the issue disappears and the `Sertny.framework.dSYM` is part of the archive.

![Image](https://github.com/user-attachments/assets/ad749a61-16d5-452e-94e4-c47150834179)
![Image](https://github.com/user-attachments/assets/e744f5f8-444b-4468-a361-b7e42b030e26)

Also found this [stackoverflow post](https://stackoverflow.com/a/73726928), describing embedding of dynamic libraries. When checking the content of the app within the archive, Sentry is also part of the `Frameworks` folder when using `Sentry-Dynamic`.

![Image](https://github.com/user-attachments/assets/9b65e211-4614-426f-b6fb-3f5b1d6ab6d1)

[andr-ec](https://github.com/andr-ec) Could you try adding with `Sentry-Dynamic` with SPM and see if this resolves your issue?

@philipphofmann Is there anything speaking against using the `Sentry-Dynamic` instead of static `Sentry`?

**Comment by brustolin** [comment]
I believe this is a misbehavior of Xcode 16. 
I have shared my findings and am waiting for help from Apple on the matter in this [forum post](https://developer.apple.com/forums/thread/761589).

**Comment by trevorturk** [comment]
@brustolin would it be possible to provide a summary of the issue and any workarounds you might suggest? I'm reading back through this issue and the forum posts, but I'm not totally clear on what's going on. Is it safe to ignore the warning, or is there an actual underlying issue? Is it recommended to use `Sentry-Dynamic` until the issue is resolved? I just can't tell if this is an errant warning that isn't a big deal, or if Sentry users need to take some action. Thank you!

**Comment by brustolin** [comment]
Hello @trevorturk, all my tests indicate that it’s perfectly safe to ignore the warning. It means that the Apple will not have symbols for Sentry SDK to use in there crash reports, which actually are not needed since it was linked statically.

If you use Sentry-Dynamic, the warning goes away, but it’s a matter of preference. One is linked dynamically, and the other is linked statically.

We’re trying to figure this out with Apple to see if there’s something we can do to get rid of the warning, or if this is an Xcode bug.

**Comment by trevorturk** [comment]
Gotcha, thank you! So, I'll just ignore and carry on for now. Sounds like something you'll be able to smooth out with Apple in the future, but shouldn't have any impact in practice. Thanks for your work on this issue! 🤘

**Comment by adilanchian** [comment]
Thanks for this thread!

Can confirm this still exists in Xcode 16 GM.

But, looks like it's not much to worry about at the moment. Will press on.

Ty!

**Comment by UnexDev** [comment]
I'm currently getting this warning on both Xcode distributions and sentry dashboard. I also have no source context. Is there a way to upload them manually?

**Comment by brustolin** [comment]
Hello @UnexDev yes, you can manually upload source context of your project.
Take a look at our documentation about it in [here](https://docs.sentry.io/platforms/apple/guides/ios/sourcecontext/).

**Comment by DataGreed** [comment]
Any updates?

**Comment by brustolin** [comment]
Hello @DataGreed, unfortunately  no, there is no update on this one.

This requires Apple to change Xcode behavior, you can follow the discussion in [here](https://developer.apple.com/forums/thread/761589).

**Comment by philprime** [comment]
There is nothing we can do for now, seems like a bug in Xcode.
